//
//  ViewController.swift
//  CustomCell
//
//  Created by Jahan Cherian on 4/4/15.
//  Copyright (c) 2015 Jahan Cherian. All rights reserved.
//

import UIKit

class HomePage: UIViewController {

//    @IBOutlet weak var myTableView: UITableView!
//    var arrayOfFood: [Food] = [Food]()
//    
    
  override func viewDidLoad() {
        super.viewDidLoad()
        self.title = "Main View"
//        
//        self.setUpFood()
//        // Do any additional setup after loading the view, typically from a nib.
 }

  override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

//    func setUpFood()
//    {
//        var food1 = Food(title: "Cold Cereal", servingTime: "BREAKFAST", foodType: "Boxed Cereal", numSwipes: "1", foodState: "Cold")
//        var food2 = Food(title: "Ham & Cheese Croissant", servingTime: "BREAKFAST", foodType: "Croissant", numSwipes: "1", foodState: "Hot")
//        var food3 = Food(title: "Spinach & Cheese Croissant", servingTime: "BREAKFAST", foodType: "Boxed Croissant", numSwipes: "1", foodState: "Hot")
//        var food4 = Food(title: "Steel-Cut Oatmeal Cup", servingTime: "BREAKFAST", foodType: "Oatmeal", numSwipes: "1", foodState: "Cold")
//        var food5 = Food(title: "Yogurt Cup", servingTime: "BREAKFAST", foodType: "Yogurt Cup", numSwipes: "1", foodState: "Cold")
//        var food6 = Food(title: "Fruit Cup", servingTime: "BREAKFAST", foodType: "Fruit Cup", numSwipes: "1", foodState: "Cold")
//        var food7 = Food(title: "Yogurt Parfait Cup", servingTime: "BREAKFAST", foodType: "Yogurt Cup", numSwipes: "1", foodState: "Cold")
//        var food8 = Food(title: "BBQ Beef Brisket", servingTime: "LUNCH AND DINNER", foodType: "Classic Sandwich", numSwipes: "1", foodState: "Toasted")
//        var food9 = Food(title: "Ham & Swiss", servingTime: "LUNCH AND DINNER", foodType: "Classic Sandwich", numSwipes: "1", foodState: "Toasted/Cold")
//        var food10 = Food(title: "Roast Beef & Cheddar", servingTime: "LUNCH AND DINNER", foodType: "Classic Sandwich", numSwipes: "1", foodState: "Toasted/Cold")
//        var food11 = Food(title: "Roasted Turkey & Provolone", servingTime: "LUNCH AND DINNER", foodType: "Classic Sandwich", numSwipes: "1", foodState: "Toasted/Cold")
//        var food12 = Food(title: "Tuna", servingTime: "LUNCH AND DINNER", foodType: "Classic Sandwich", numSwipes: "1", foodState: "Cold")
//        var food13 = Food(title: "Vegan BBQ", servingTime: "LUNCH AND DINNER", foodType: "Premium Sandwich", numSwipes: "1", foodState: "Toasted")
//        var food14 = Food(title: "Chicken Ranch & Swiss", servingTime: "LUNCH AND DINNER", foodType: "Premium Sandwich", numSwipes: "1", foodState: "Toasted")
//        var food15 = Food(title: "Chipotle BBQ Turkey", servingTime: "LUNCH AND DINNER", foodType: "Premium Sandwich", numSwipes: "1", foodState: "Toasted")
//        var food16 = Food(title: "Cuban Ham", servingTime: "LUNCH AND DINNER", foodType: "Premium Sandwich", numSwipes: "1", foodState: "Toasted")
//        var food17 = Food(title: "Honey Mustard Chicken Bacon", servingTime: "LUNCH AND DINNER", foodType: "Premium Sandwich", numSwipes: "2", foodState: "Toasted")
//        var food18 = Food(title: "Pastrami & Cheese", servingTime: "LUNCH AND DINNER", foodType: "Premium Sandwich", numSwipes: "2", foodState: "Toasted")
//        var food19 = Food(title: "Chunky Chicken Salad", servingTime: "LUNCH AND DINNER", foodType: "Premium Sandwich", numSwipes: "1", foodState: "Cold")
//        var food20 = Food(title: "Roasted Vegetable & Hummus", servingTime: "LUNCH AND DINNER", foodType: "Premium Sandwich", numSwipes: "1", foodState: "Cold")
//        var food21 = Food(title: "The Greek Vegetable", servingTime: "LUNCH AND DINNER", foodType: "Premium Sandwich", numSwipes: "1", foodState: "Cold")
//        var food22 = Food(title: "California Turkey Club", servingTime: "LUNCH AND DINNER", foodType: "Premium Sandwich", numSwipes: "2", foodState: "Cold")
//        var food23 = Food(title: "Hawaiin Ham", servingTime: "LUNCH AND DINNER", foodType: "Premium Sandwich", numSwipes: "2", foodState: "Cold")
//        var food24 = Food(title: "Grilled Steak", servingTime: "LUNCH AND DINNER", foodType: "Kosher Sandwich", numSwipes: "2", foodState: "Hot")
//        var food25 = Food(title: "Grilled Wild Salmon", servingTime: "LUNCH AND DINNER", foodType: "Kosher Sandwich", numSwipes: "2", foodState: "Hot")
//        var food26 = Food(title: "Italian Minestrone", servingTime: "LUNCH AND DINNER - All day", foodType: "Entrée Soups", numSwipes: "1", foodState: "Hot Soup & Bread Bowl")
//        var food27 = Food(title: "New England Clam Chowder", servingTime: "LUNCH AND DINNER - All day", foodType: "Entrée Soups", numSwipes: "1", foodState: "Hot Soup & Bread Bowl")
//        var food28 = Food(title: "Beef Noodle Soup", servingTime: "LUNCH AND DINNER - SUNDAYS", foodType: "Entrée Soups", numSwipes: "1", foodState: "Hot Soup & Bread Bowl")
//        var food29 = Food(title: "Cream of Tomato", servingTime: "LUNCH AND DINNER - MONDAYS", foodType: "Entrée Soups", numSwipes: "1", foodState: "Hot Soup & Bread Bowl")
//        var food30 = Food(title: "Cream of Carrot & Dill", servingTime: "LUNCH AND DINNER - TUESDAYS", foodType: "Entrée Soups", numSwipes: "1", foodState: "Hot Soup & Bread Bowl")
//        var food31 = Food(title: "Ground Beef Chilli", servingTime: "LUNCH AND DINNER - WEDNESDAYS", foodType: "Entrée Soups", numSwipes: "1", foodState: "Hot Soup & Bread Bowl")
//        var food32 = Food(title: "Chicken Noodle", servingTime: "LUNCH AND DINNER - THURSDAYS", foodType: "Entrée Soups", numSwipes: "1", foodState: "Hot Soup & Bread Bowl")
//        var food33 = Food(title: "Shrimp & Corn Chowder", servingTime: "LUNCH AND DINNER - FRIDAYS", foodType: "Entrée Soups", numSwipes: "1", foodState: "Hot Soup & Bread Bowl")
//        var food34 = Food(title: "Vegan Chilli", servingTime: "LUNCH AND DINNER - SATURDAYS", foodType: "Entrée Soups", numSwipes: "1", foodState: "Hot Soup & Bread Bowl")
//        var food35 = Food(title: "Chicken Caesar Wrap", servingTime: "LUNCH AND DINNER", foodType: "On The Go Wraps", numSwipes: "1", foodState: "Cold")
//        var food36 = Food(title: "BBQ Chicken", servingTime: "LUNCH AND DINNER", foodType: "On The Go Specialty Wraps", numSwipes: "1", foodState: "Cold")
//        var food37 = Food(title: "Chicken Caesar", servingTime: "LUNCH AND DINNER", foodType: "On The Go Specialty Wraps", numSwipes: "1", foodState: "Cold")
//        var food38 = Food(title: "Southwest Black Bean & Corn", servingTime: "LUNCH AND DINNER", foodType: "On The Go Specialty Wraps", numSwipes: "1", foodState: "Cold")
//        var food39 = Food(title: "Southwest Chicken", servingTime: "LUNCH AND DINNER", foodType: "On The Go Specialty Wraps", numSwipes: "1", foodState: "Cold")
//        var food40 = Food(title: "Caesar Salad", servingTime: "LUNCH AND DINNER", foodType: "On The Go Salads & More", numSwipes: "1", foodState: "Cold")
//        var food41 = Food(title: "Chicken & Bacon Gorgonzola Salad", servingTime: "LUNCH AND DINNER", foodType: "On The Go Salads & More", numSwipes: "1", foodState: "Cold")
//        var food42 = Food(title: "Chicken Caesar Salad", servingTime: "LUNCH AND DINNER", foodType: "On The Go Salads & More", numSwipes: "1", foodState: "Cold")
//        var food43 = Food(title: "Chinese Chicken Salad", servingTime: "LUNCH AND DINNER", foodType: "On The Go Salads & More", numSwipes: "1", foodState: "Cold")
//        var food44 = Food(title: "Chinese Wonton Salad", servingTime: "LUNCH AND DINNER", foodType: "On The Go Salads & More", numSwipes: "1", foodState: "Cold")
//        var food45 = Food(title: "Meditarranean Nachos", servingTime: "LUNCH AND DINNER", foodType: "On The Go Salads & More", numSwipes: "1", foodState: "Hot")
//        var food46 = Food(title: "Mixed Field Greens with Apples & Berries", servingTime: "LUNCH AND DINNER", foodType: "On The Go Salads & More", numSwipes: "1", foodState: "Cold")
//        var food47 = Food(title: "Tuna Salad ", servingTime: "LUNCH AND DINNER", foodType: "On The Go Salads & More", numSwipes: "1", foodState: "Hot")
//        var food48 = Food(title: "Asian Quinoa Salad ", servingTime: "LUNCH AND DINNER", foodType: "Sides", numSwipes: "Available with Order", foodState: "Cold")
//        var food49 = Food(title: "California Pasta Salad ", servingTime: "LUNCH AND DINNER", foodType: "Sides", numSwipes: "Available with Order", foodState: "Cold")
//        var food50 = Food(title: "Cranberry Relish ", servingTime: "LUNCH AND DINNER", foodType: "Sides", numSwipes: "Available with Order", foodState: "Cold")
//        var food51 = Food(title: "Israeli Cous Cous Salad ", servingTime: "LUNCH AND DINNER", foodType: "Sides", numSwipes: "Available with Order", foodState: "Cold")
//        var food52 = Food(title: "Mediterranean Chopped Salad ", servingTime: "LUNCH AND DINNER", foodType: "Sides", numSwipes: "Available with Order", foodState: "Cold")
//        var food53 = Food(title: "Seasame & Orange Noodle Salad ", servingTime: "LUNCH AND DINNER", foodType: "Sides", numSwipes: "Available with Order", foodState: "Cold")
//        var food54 = Food(title: "Fresh Fruit Cup ", servingTime: "ALL DAY", foodType: "Sides & Sweets", numSwipes: "1", foodState: "Cold")
//        var food55 = Food(title: "Yogurt Parfait Cup ", servingTime: "ALL DAY", foodType: "Sides & Sweets", numSwipes: "1", foodState: "Cold")
//        var food56 = Food(title: "Banana ", servingTime: "ALL DAY", foodType: "Sides & Sweets", numSwipes: "Available wiht Order", foodState: "Cold")
//        var food57 = Food(title: "Apple ", servingTime: "ALL DAY", foodType: "Sides & Sweets", numSwipes: "Available with Order", foodState: "Cold")
//        var food58 = Food(title: "Orange", servingTime: "ALL DAY", foodType: "Sides & Sweets", numSwipes: "Available with Order", foodState: "Cold")
//        var food59 = Food(title: "Boulder Canyon Totally Natural Kettle Chips ", servingTime: "ALL DAY", foodType: "Sides & Sweets", numSwipes: "Available with Order", foodState: "Cold")
//        var food60 = Food(title: " SunChips ", servingTime: "ALL DAY", foodType: "Sides & Sweets", numSwipes: "Available with Order", foodState: "Cold")
//        var food61 = Food(title: "Poore Brothers Jalapeno Kettle Chips ", servingTime: "ALL DAY", foodType: "Sides & Sweets", numSwipes: "Available with Order", foodState: "Cold")
//        
//        var food62 = Food(title: "Brewed Coffee ", servingTime: "ALL DAY", foodType: "Coffee & Tea", numSwipes: "1", foodState: "Hot/Cold")
//        var food63 = Food(title: "Cafe Mocha ", servingTime: "ALL DAY", foodType: "Coffee & Tea", numSwipes: "1", foodState: "Hot/Cold")
//        var food64 = Food(title: "Cafe Vanilla ", servingTime: "ALL DAY", foodType: "Coffee & Tea", numSwipes: "1", foodState: "Hot/Cold")
//        var food65 = Food(title: "Cafe Caramel ", servingTime: "ALL DAY", foodType: "Coffee & Tea", numSwipes: "1", foodState: "Hot/Cold")
//        var food66 = Food(title: "Cafe Latte ", servingTime: "ALL DAY", foodType: "Coffee & Tea", numSwipes: "1", foodState: "Hot/Cold")
//        var food67 = Food(title: "Mocha Latte ", servingTime: "ALL DAY", foodType: "Coffee & Tea", numSwipes: "1", foodState: "Hot/Cold")
//        var food68 = Food(title: "Vanilla Latte ", servingTime: "ALL DAY", foodType: "Coffee & Tea", numSwipes: "1", foodState: "Hot/Cold")
//        var food69 = Food(title: "Caramel Latte ", servingTime: "ALL DAY", foodType: "Coffee & Tea", numSwipes: "1", foodState: "Hot/Cold")
//        var food70 = Food(title: "White Chocolate Latte ", servingTime: "ALL DAY", foodType: "Coffee & Tea", numSwipes: "1", foodState: "Hot/Cold")
//        var food71 = Food(title: "Cappuccino ", servingTime: "ALL DAY", foodType: "Coffee & Tea", numSwipes: "1", foodState: "Hot/Cold")
//        var food72 = Food(title: "Hot Chocolate ", servingTime: "ALL DAY", foodType: "Coffee & Tea", numSwipes: "1", foodState: "Hot")
//        var food73 = Food(title: "Hot Vanilla ", servingTime: "ALL DAY", foodType: "Coffee & Tea", numSwipes: "1", foodState: "Hot")
//        var food74 = Food(title: "Brewed Tea ", servingTime: "ALL DAY", foodType: "Coffee & Tea", numSwipes: "1", foodState: "Hot")
//        var food75 = Food(title: "Tea Latte ", servingTime: "ALL DAY", foodType: "Coffee & Tea", numSwipes: "1", foodState: "Hot")
//        var food76 = Food(title: "Chai Tea Latte ", servingTime: "ALL DAY", foodType: "Coffee & Tea", numSwipes: "1", foodState: "Hot/Cold")
//        var food77 = Food(title: "Americano ", servingTime: "ALL DAY", foodType: "Coffee & Tea", numSwipes: "1", foodState: "Hot/Cold")
//        var food78 = Food(title: "Expresso ", servingTime: "ALL DAY", foodType: "Coffee & Tea", numSwipes: "1", foodState: "Hot")
//        var food79 = Food(title: "Apple Turnover ", servingTime: "ALL DAY", foodType: "Pastry", numSwipes: ".5", foodState: "Cold")
//        var food80 = Food(title: "Assorted Bagels ", servingTime: "ALL DAY", foodType: "Pastry", numSwipes: ".5", foodState: "Cold")
//        var food81 = Food(title: "Assorted Muffins ", servingTime: "ALL DAY", foodType: "Pastry", numSwipes: ".5", foodState: "Cold")
//        var food82 = Food(title: "Assorted Scones ", servingTime: "ALL DAY", foodType: "Pastry", numSwipes: ".5", foodState: "Cold")
//        var food83 = Food(title: "Assorted Cupcakes ", servingTime: "ALL DAY", foodType: "Pastry", numSwipes: ".5", foodState: "Cold")
//        var food84 = Food(title: "Assorted Croissants ", servingTime: "ALL DAY", foodType: "Pastry", numSwipes: ".5", foodState: "Cold")
//        var food85 = Food(title: "Assorted Turnovers ", servingTime: "ALL DAY", foodType: "Pastry", numSwipes: ".5", foodState: "Cold")
//        var food86 = Food(title: "Assorted Cookies ", servingTime: "ALL DAY", foodType: "Pastry", numSwipes: ".5", foodState: "Cold")
//        var food87 = Food(title: "Cinnamon Roll ", servingTime: "ALL DAY", foodType: "Pastry", numSwipes: ".5", foodState: "Cold")
//        var food88 = Food(title: "Cirtrus Teacake ", servingTime: "ALL DAY", foodType: "Pastry", numSwipes: ".5", foodState: "Cold")
//        var food89 = Food(title: "Grandma's Banana Bread ", servingTime: "ALL DAY", foodType: "Pastry", numSwipes: ".5", foodState: "Cold")
//        var food90 = Food(title: "Marble Loaf Cake ", servingTime: "ALL DAY", foodType: "Pastry", numSwipes: ".5", foodState: "Cold")
//        var food91 = Food(title: "Palmier/Crispy", servingTime: "ALL DAY", foodType: "Pastry", numSwipes: ".5", foodState: "Cold")
//        var food92 = Food(title: "Raspberry Danish ", servingTime: "ALL DAY", foodType: "Pastry", numSwipes: ".5", foodState: "Cold")
//        var food93 = Food(title: "Wolferman English Muffin ", servingTime: "ALL DAY", foodType: "Pastry", numSwipes: ".5", foodState: "Cold")
//        var food94 = Food(title: "World's Best Coffee Cake ", servingTime: "ALL DAY", foodType: "Pastry", numSwipes: ".5", foodState: "Cold")
//        
//        arrayOfFood.append(food1)
//        arrayOfFood.append(food2)
//        arrayOfFood.append(food4)
//        arrayOfFood.append(food5)
//        arrayOfFood.append(food6)
//        arrayOfFood.append(food7)
//        arrayOfFood.append(food8)
//        arrayOfFood.append(food9)
//        arrayOfFood.append(food10)
//        arrayOfFood.append(food11)
//        arrayOfFood.append(food12)
//        arrayOfFood.append(food13)
//        arrayOfFood.append(food14)
//        arrayOfFood.append(food15)
//        arrayOfFood.append(food16)
//        arrayOfFood.append(food17)
//        arrayOfFood.append(food18)
//        arrayOfFood.append(food19)
//        arrayOfFood.append(food20)
//        arrayOfFood.append(food21)
//        arrayOfFood.append(food22)
//        arrayOfFood.append(food23)
//        arrayOfFood.append(food24)
//        arrayOfFood.append(food25)
//        arrayOfFood.append(food26)
//        arrayOfFood.append(food27)
//        arrayOfFood.append(food28)
//        arrayOfFood.append(food29)
//        arrayOfFood.append(food30)
//        arrayOfFood.append(food31)
//        arrayOfFood.append(food32)
//        arrayOfFood.append(food33)
//        arrayOfFood.append(food34)
//        arrayOfFood.append(food35)
//        arrayOfFood.append(food36)
//        arrayOfFood.append(food37)
//        arrayOfFood.append(food38)
//        arrayOfFood.append(food39)
//        arrayOfFood.append(food40)
//        arrayOfFood.append(food41)
//        arrayOfFood.append(food42)
//        arrayOfFood.append(food43)
//        arrayOfFood.append(food44)
//        arrayOfFood.append(food45)
//        arrayOfFood.append(food46)
//        arrayOfFood.append(food47)
//        arrayOfFood.append(food48)
//        arrayOfFood.append(food49)
//        arrayOfFood.append(food50)
//        arrayOfFood.append(food51)
//        arrayOfFood.append(food52)
//        arrayOfFood.append(food53)
//        arrayOfFood.append(food54)
//        arrayOfFood.append(food55)
//        arrayOfFood.append(food56)
//        arrayOfFood.append(food57)
//        arrayOfFood.append(food58)
//        arrayOfFood.append(food59)
//        arrayOfFood.append(food60)
//        arrayOfFood.append(food61)
//        arrayOfFood.append(food62)
//        arrayOfFood.append(food63)
//        arrayOfFood.append(food64)
//        arrayOfFood.append(food65)
//        arrayOfFood.append(food66)
//        arrayOfFood.append(food67)
//        arrayOfFood.append(food68)
//        arrayOfFood.append(food69)
//        arrayOfFood.append(food70)
//        arrayOfFood.append(food71)
//        arrayOfFood.append(food72)
//        arrayOfFood.append(food73)
//        arrayOfFood.append(food74)
//        arrayOfFood.append(food75)
//        arrayOfFood.append(food76)
//        arrayOfFood.append(food77)
//        arrayOfFood.append(food78)
//        arrayOfFood.append(food79)
//        arrayOfFood.append(food80)
//        arrayOfFood.append(food81)
//        arrayOfFood.append(food82)
//        arrayOfFood.append(food83)
//        arrayOfFood.append(food84)
//        arrayOfFood.append(food85)
//        arrayOfFood.append(food86)
//        arrayOfFood.append(food87)
//        arrayOfFood.append(food88)
//        arrayOfFood.append(food89)
//        arrayOfFood.append(food90)
//        arrayOfFood.append(food91)
//        arrayOfFood.append(food92)
//        arrayOfFood.append(food93)
//        arrayOfFood.append(food94)
//    }
   
//    func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
//        return arrayOfFood.count
//    }
//    
//    func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell
//    {
//        var cell: CustomCell = self.myTableView.dequeueReusableCellWithIdentifier("myCustomCell", forIndexPath: indexPath) as CustomCell
//        let food = arrayOfFood[indexPath.row]
//        cell.setCell(food.title, servingTimeText: food.servingTime, foodTypeText: food.foodType, numSwipesInt: food.numSwipes, foodStateText: food.foodState)
//        
//        return cell
//    }
//}
}
